org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.79
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=materialist
mod_name=MateriaList
mod_license=MIT License
mod_version=0.0.0
mod_group_id=net.timeworndevs.materialist
mod_authors={VoxelDragon6} (Lead)
mod_description=MateriaList: Every material in one place.\nThis mod aims to add nearly every material used by most mods in one cohesive project, as well as shoring up a few loose ends.\nUnlike most mods, every texture is hand-made instead of generated, and if anyone wants to add their own material, there is a built-in API to do so!
